#!/bin/sh

PROJECTS="/projects"
TEMPLATES="$PROJECTS/templates"

TO_USER=infra
TO_HOST=sankhara

while [ -n "$1" ]; do
	case "$1" in
		-h)
			TO_HOST="$2"
			shift
			shift
			;;
		-u)
			TO_USER="$2"
			shift
			shift
			;;
		*)
			break
			;;
	esac
done

if [ -z "$1" ]; then
	echo "Usage: $0 <project> [username]" >&2
	exit 1
fi

NAME="$1"
if [ -n "$2" ]; then
	PROJECT_USER="$2"
else
	PROJECT_USER="$LOGNAME"
fi

if [ ! -f $PROJECTS/$NAME/$TO_HOST/etc/bashrc-$PROJECT_USER ]; then
	echo "$0: No known user given" >&2
	echo "Usage: $0 <project> [username]" >&2
	exit 1
fi

chroot $PROJECTS/$NAME/$TO_HOST su - $TO_USER -c /knsetup/bootstrap-shell.sh $PROJECT_USER
