#!/bin/sh

if [ -z "$1" ]; then
        echo "Usage: $0 <jille|bas|bram|--unset>" >&2
        exit 1
fi

case "$1" in
        jille)
                git config user.name "Jille Timmermans"
                git config user.email jille@karpenoktem.nl
        ;;
        bas)
                git config user.name "Bas Westerbaan"
                git config user.email bas@karpenoktem.nl
        ;;
        peter|petervdv)
                git config user.name "Peter van der Veeken"
                git config user.email petervdv@karpenoktem.nl
        ;;
        bram|bramw)
                git config user.name "Bram Westerbaan"
                git config user.email bramw@karpenoktem.nl
        ;;
        daan|daansp)
                git config user.name "Daan Sprenkels"
                git config user.email daansp@karpenoktem.nl
        ;;
        rik)
                git config user.name "Rik Sprenkels"
                git config user.email rik@karpenoktem.nl
        ;;
        felix)
                git config user.name "Felix Janssen"
                git config user.email felix@karpenoktem.nl
        ;;
        ayke)
                git config user.name "Ayke van Laethem"
                git config user.email ayke@karpenoktem.nl
        ;;
        --unset)
                git config --unset user.name
                git config --unset user.email
        ;;
        *)
                echo "$0: Invalid user: $1" >&2
                exit 1
esac
